### ISSUE TITLE
Hangs on message publish if nsqd connection is suddenly closed

### ISSUE THREAD

**Issue by atugushev** [list-family/ansq#25]
#### Environment Versions

1. Python version: `Python 3.8.0`
1. ansq version: `0.0.16`

#### Steps to replicate

1. Run the following script:
```python
import time
import asyncio
from ansq import open_connection


async def main():
    nsq = await open_connection()
    print('Connected')
    time.sleep(5)  # <--- stop `nsqd` at this point
    print(await nsq.pub('test_topic', 'test_message_in'))
    await nsq.close()


if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())
```

2. Stop `nsqd` at `time.sleep(5)`.
3. The script hangs

#### Expected result

It should try to reconnect and raise an Exception if no success.

#### Actual result

```
Connected
2020-09-07 15:25:09,965 - ERROR - ansq localhost:4150.0: Connection tcp://localhost:4150 is closing due an error: [Errno 54] Connection reset by peer
^CTraceback (most recent call last):
  File "t3.py", line 16, in <module>
    loop.run_until_complete(main())
  File "/Users/albert/.pyenv/versions/3.8.0/lib/python3.8/asyncio/base_events.py", line 595, in run_until_complete
    self.run_forever()
  File "/Users/albert/.pyenv/versions/3.8.0/lib/python3.8/asyncio/base_events.py", line 563, in run_forever
    self._run_once()
  File "/Users/albert/.pyenv/versions/3.8.0/lib/python3.8/asyncio/base_events.py", line 1808, in _run_once
    event_list = self._selector.select(timeout)
  File "/Users/albert/.pyenv/versions/3.8.0/lib/python3.8/selectors.py", line 558, in select
    kev_list = self._selector.control(None, max_ev, timeout)
KeyboardInterrupt.
```

<kbd>^C</kbd> stopped the script

**Comment by atugushev** [comment]
I've researched it a little, looks like it hangs on https://github.com/list-family/ansq/blob/c5c1dcdfd516348377342877b548b8c8e5ed6183/ansq/tcp/connection.py#L184
